
    link: "Link("link_first")" | "Link("link_first", "link_rest")"
    
    ?link_first: NUMBER | link
    
    ?link_rest: link | "null" | NUMBER
    
    %ignore /\s+/
    %import common.NUMBER


?start: tree_node    
    tree_node: "Tree("label")" | "Tree("label", ""["branches"]"")" 
    
    ?label: NUMBER
    
    branches: tree_node | label | tree_node ", " tree_node
    
    %ignore /\s+/
    %import common.NUMBER




